<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PF1RBSPR" failures="1" tests="1" name="Default test" time="9.903" errors="0" timestamp="08 Jan 2020 19:56:24 GMT">
  <testcase classname="SapTests.IntegrationTestsSapWeb" name="integrationTestSap" time="9.814">
    <failure type="com.jacob.com.ComFailException" message="Invoke of: findById
Source: SAP Frontend Server
Description: The control could not be found by id.
">
      <![CDATA[com.jacob.com.ComFailException: Invoke of: findByIdSource: SAP Frontend ServerDescription: The control could not be found by id.at com.jacob.com.Dispatch.invokev(Native Method)at com.jacob.com.Dispatch.invokev(Dispatch.java:625)at com.jacob.com.Dispatch.callN(Dispatch.java:453)at com.jacob.com.Dispatch.call(Dispatch.java:541)at com.jacob.activeX.ActiveXComponent.invoke(ActiveXComponent.java:402)at SapAppmanager.HelperBase.findById(HelperBase.java:17)at SapAppmanager.HelperBase.makeAction(HelperBase.java:30)at SapDocuments.PurchaseOrder.createSapDoc(PurchaseOrder.java:165)at SapTests.IntegrationTestsSapWeb.integrationTestSap(IntegrationTestsSapWeb.java:62)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:567)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- integrationTestSap -->
</testsuite> <!-- Default test -->
